trying with javafx

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,27 +1,26 @@
-#!/usr/bin/env ruby
-# frozen_string_literal: true
+#!/usr/bin/env bash
 
-# Cloud Foundry Java Buildpack
-# Copyright 2013-2018 the original author or authors.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+# fail fast
+set -eu
 
-$stdout.sync = true
-$stderr.sync = true
-$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
+# parse args
+BP_DIR="$(cd "$(dirname "$0")" && pwd)"
+BUILD_DIR=$1
+OPT_DIR=$BP_DIR/../opt/
 
-require 'java_buildpack/buildpack'
+cd $BUILD_DIR
 
-app_dir = ARGV[0]
+curl --retry 3 -s -o javafx.zip -L https://chriswhocodes.com/downloads/openjfx-8u60-sdk-overlay-linux-amd64.zip
 
-JavaBuildpack::Buildpack.with_buildpack(app_dir, 'Compile failed with exception %s', &:compile)
+if [ -d .jdk ]; then
+  echo -n "       Extracting OpenJFX ... "
+  unzip javafx.zip -d .jdk > /dev/null 2>&1
+else
+  echo -n "       Extracting OpenJFX to .jdk-overlay/ ... "
+  unzip javafx.zip -d .jdk-overlay > /dev/null 2>&1
+fi
+echo "done"
+
+rm javafx.zip
+
+ruby compile-ruby
